{% set name = "jupytercad" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2dd55491d06e988b910cb5433d4c4c7080c8a9e8e2778aa4d7e86db6ae19c63f

build:
  noarch: python
  number: 0


outputs:
  - name: jupytercad_core
    version: {{ version }}
    build:
      script: |
        cd python/jupytercad_core
        python -m pip install . -vv --no-deps
    requirements:
      host:
        - python >=3.8
        - hatchling
        - pip
      run:
        - python >=3.8
        - jupyter_server >=2.0.6,<3
        - jupyter_ydoc >=1.1,<2
        - y-py >=0.6,<0.7
        - jupyter-collaboration >=1.2,<2
    test:
      imports:
        - jupytercad_code.jcad_ydoc.YJCad
        - jupytercad_code.step_ydoc.YSTEP
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-core/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-core\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytercad_lab
    version: {{ version }}
    build:
      script: |
        cd python/jupytercad_lab
        python -m pip install . -vv --no-deps
    requirements:
      host:
        - python >=3.8
        - hatchling
        - jupyterlab >=4,<5
        - hatch-nodejs-version >=0.3.2
        - pip
      run:
        - python >=3.8
        - jupyter_server> =2.0.1,<3
        - jupyter_ydoc >=1.1,<2
        - y-py >=0.6,<0.7
        - jupyter_collaboration >=1,<2
        - ypywidgets >=0.4.1,<0.5
        - yjs-widgets >=0.3.4,<0.4
        - comm >=0.1.2,<0.2
        - pydantic >=2,<3
        - jupytercad_core
      run_constrained:
        - jupyterlab >=4,<5
        - jupytercad_core =={{ version }}
    test:
      imports:
        - jupytercad_lab.notebook.cad_document
      commands:
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-lab/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@jupytercad/jupytercad-lab\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytercad_app
    version: {{ version }}
    build:
      script: |
        cd python/jupytercad_app
        python -m pip install . -vv --no-deps
    entry_points:
      - jupyter-cad = jupytercad_app.cadapp:main
    requirements:
      host:
        - python >=3.8
        - hatchling
        - pip
      run:
        - python >=3.8
        - jupyter_server >=2.0.1,<3
        - jupytercad_core
        - jupytercad_lab
      run_constrained:
        - jupyterlab >=4,<5
        - jupytercad_lab =={{ version }}
        - jupytercad_core =={{ version }}
    test:
      imports:
        - jupytercad_app.cadapp.main
      commands:
        - jupyter cad --version
        - pip check
        - test -f ${PREFIX}/share/jupyter/labextensions/@jupytercad/jupytercad-app/package.json                            # [unix]
        - if not exist %PREFIX%\\share\\jupyter\\appextensions\\@jupytercad/jupytercad-lab\\package.json (exit 1)          # [win]
      requires:
        - pip

  - name: jupytercad
    version: {{ version }}
    build:
      script: |
        cd python/jupytercad
        python -m pip install . -vv --no-deps
    requirements:
      host:
        - python >=3.8
        - hatchling
        - pip
      run:
        - python >=3.8
        - jupytercad_core
        - jupytercad_lab
        - jupytercad_app
      run_constrained:
        - jupytercad_core =={{ version }}
        - jupytercad_lab =={{ version }}
        - jupytercad_app =={{ version }}
    test:
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/QuantStack/jupytercad
  summary: A JupyterLab extension for 3D geometry modeling
  description: |
    JupyterCAD is a JupyterLab extension for 3D geometry modeling with collaborative editing support. It is designed to allow multiple people to work on the same file at the same time, and to facilitate discussion and collaboration around the 3D shapes being created.
    JupyterCAD has support for FreeCAD files, which makes it easy to import and export models from FreeCAD. It also has a range of features for creating and manipulating 3D shapes, including a variety of primitives, transformations, and Boolean operations.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://jupytercad.readthedocs.io/en/latest
  dev_url: https://github.com/QuantStack/jupytercad

extra:
  recipe-maintainers:
    - martinRenou
    - trungleduc
